import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ICONS: Array<{ filename: string; size: number; base64: string }> = [
  {
    filename: 'icon-192.png',
    size: 192,
    base64: `
iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAABiklEQVR42u3TMQ0A
AAjAMBxw4gH//sAEHz1qYMkiqwe+ChEwABgADAAGAAOAAcAAYAAwABgADAAGAAOA
AcAAYAAwABgADAAGAAOAAcAAYAAwABgADAAGAAOAAcAAYAAwABgADAAGAAOAAcAA
YAAwABgADAAGAAOAAcAAYAAwABgADIABRMAAYAAwABgADAAGAAOAAcAAYAAwABgA
DAAGAAOAAcAAYAAwABgADAAGAAOAAcAAYAAwABgADAAGAAOAAcAAYAAwABgADAAG
AAOAAcAAYAAwABgADAAGAAOAAcAAYAAwAAYAA4ABwABgADAAGAAMAAYAA4ABwABg
ADAAGAAMAAYAA4ABwABgADAAGAAMAAYAA4ABwABgADAAGAAMAAYAA4ABwABgADAA
GAAMAAYAA4ABwABgADAAGAAMAAYAA4ABMIAIGAAMAAYAA4ABwABgADAAGAAMAAYA
A4ABwABgADAAGAAMAAYAA4ABwABgADAAGAAMAAYAA4ABwABgADAAGAAMAAaASwsd
Q3sFUwQJzwAAAABJRU5ErkJggg==
`
  },
  {
    filename: 'icon-512.png',
    size: 512,
    base64: `
iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAG40lEQVR42u3WIQEA
AAjAMBog6UD/flACx8QKXD2yegCAX0IEADAAAIABAAAMAABgAAAAAwAAGAAAwAAA
AAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAGAAAAADAAAYAADAAAAA
BgAAMAAAgAEAAAwAAGAAAAADAAAYAADAAAAABgAAMAAAgAEAAAwAAGAAAMAAAAAG
AAAwAACAAQAADAAAYAAAAAMAABgAAMAAAAAGAAAwAACAAQAADAAAYAAAAAMAABgA
AMAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAA
wAAAAAYAADAAAIABAAADIAQAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAA
wAAAAAYAADAAAIABAAAMAABgAAAAAwAABkAEADAAAIABAAAMAABgAAAAAwAAGAAA
wAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAGAAAAADAAAYAADA
AAAABgAAMAAAgAEAAAwAAGAAAAADAAAYAADAAAAABgAAMAAAgAEAAAwAAGAAAMAA
AAAGAAAwAACAAQAADAAAYAAAAAMAABgAAMAAAAAGAAAwAACAAQAADAAAYAAAAAMA
ABgAAMAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAA
GAAAwAAAAAYAADAAAIABAAADIAQAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAA
GAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAABkAEADAAAIABAAAMAABgAAAAAwAA
GAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAGAAAAADAAAY
AADAAAAABgAAMAAAgAEAAAwAAGAAAAADAAAYAADAAAAABgAAMAAAgAEAAAwAAGAA
AMAAAAAGAAAwAACAAQAADAAAYAAAAAMAABgAAMAAAAAGAAAwAACAAQAADAAAYAAA
AAMAABgAAMAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAA
AwAAGAAAwAAAAAYAADAAAIABAAADIAQAGAAAwAAAAAYAADAAAIABAAAMAABgAAAA
AwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAABkAEADAAAIABAAAMAABgAAAA
AwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAGAAAAAD
AAAYAADAAAAABgAAMAAAgAEAAAwAAGAAAAADAAAYAADAAAAABgAAMAAAgAEAAAwA
AGAAAMAAAAAGAAAwAACAAQAADAAAYAAAAAMAABgAAMAAAAAGAAAwAACAAQAADAAA
YAAAAAMAABgAAMAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABg
AAAAAwAAGAAAwAAAAAYAADAAAIABAAADIAQAGAAAwAAAAAYAADAAAIABAAAMAABg
AAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAABkAEADAAAIABAAAMAABg
AAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAGAA
AAADAAAYAADAAAAABgAAMAAAgAEAAAwAAGAAAAADAAAYAADAAAAABgAAMAAAgAEA
AAwAAGAAAMAAAAAGAAAwAACAAQAADAAAYAAAAAMAABgAAMAAAAAGAAAwAACAAQAA
DAAAYAAAAAMAABgAAMAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAM
AABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAADIAQAGAAAwAAAAAYAADAAAIABAAAM
AABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAABkAEADAAAIABAAAM
AABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAA
AGAAAAADAAAYAADAAAAABgAAMAAAgAEAAAwAAGAAAAADAAAYAADAAAAABgAAMAAA
gAEAAAwAAGAAAMAAAAAGAAAwAACAAQAADAAAYAAAAAMAABgAAMAAAAAGAAAwAACA
AQAADAAAYAAAAAMAABgAAMAAAIABAAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIAB
AAAMAABgAAAAAwAAGAAAwAAAAAYAADAAAIABAAADIAQAGAAAwAAAAAYAADAAAIAB
AAAMAABgAAAAAwAAGAAAwAAAAAYAALizBPNOhYgtpTgAAAAASUVORK5CYII=
`
  }
];

async function main() {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const outputDir = join(__dirname, '..', 'apps', 'web', 'public', 'icons');

  await mkdir(outputDir, { recursive: true });

  await Promise.all(
    ICONS.map(async ({ filename, base64, size }) => {
      const filePath = join(outputDir, filename);
      const buffer = Buffer.from(base64.replace(/\s+/g, ''), 'base64');
      await writeFile(filePath, buffer);
      console.log(`Generated ${size}x${size} icon at ${filePath}`);
    })
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
